name: VarDiff
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - absl-py=2.1.0
  - aiohappyeyeballs=2.4.0
  - aiohttp=3.10.5
  - aiosignal=1.2.0
  - aom=3.6.0
  - asttokens=2.0.5
  - async-timeout=4.0.3
  - attrs=24.2.0
  - backcall=0.2.0
  - blas=1.0
  - blinker=1.6.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.2.25
  - cachetools=5.3.3
  - cairo=1.16.0
  - certifi=2024.8.30
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - click=8.1.7
  - contourpy=1.0.5
  - cryptography=43.0.0
  - cudatoolkit=11.3.1
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - dbus=1.13.18
  - easydict=1.13
  - executing=0.8.3
  - expat=2.7.1
  - ffmpeg=6.1.1
  - fontconfig=2.14.1
  - fonttools=4.51.0
  - freetype=2.13.3
  - frozenlist=1.4.0
  - giflib=5.2.2
  - glib=2.78.4
  - glib-tools=2.78.4
  - google-auth=2.29.0
  - google-auth-oauthlib=0.5.2
  - graphite2=1.3.14
  - grpcio=1.62.2
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - harfbuzz=10.2.0
  - icu=73.1
  - idna=3.7
  - imageio=2.33.1
  - importlib-metadata=7.0.1
  - importlib_resources=6.4.0
  - intel-openmp=2023.1.0
  - ipdb=0.13.13
  - ipython=8.12.2
  - jedi=0.19.1
  - joblib=1.4.2
  - jpeg=9e
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - leptonica=1.82.0
  - lerc=4.0.0
  - libabseil=20240116.2
  - libarchive=3.7.7
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcups=2.4.2
  - libcurl=8.12.1
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.4
  - libgomp=11.2.0
  - libgrpc=1.62.2
  - libiconv=1.16
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libogg=1.3.5
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=4.25.3
  - libssh2=1.11.1
  - libstdcxx-ng=11.2.0
  - libtheora=1.1.1
  - libtiff=4.7.0
  - libuuid=1.41.5
  - libvorbis=1.3.7
  - libvpx=1.13.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxkbcommon=1.9.1
  - libxml2=2.13.8
  - lz4-c=1.9.4
  - markdown=3.4.1
  - markupsafe=2.1.3
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - multidict=6.0.4
  - mysql=8.4.0
  - ncurses=6.4
  - numpy=1.24.3
  - numpy-base=1.24.3
  - oauthlib=3.2.2
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openssl=3.0.16
  - packaging=24.1
  - parso=0.8.3
  - pcre2=10.42
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.2
  - pixman=0.40.0
  - platformdirs=3.10.0
  - ply=3.11
  - pooch=1.7.0
  - prompt-toolkit=3.0.43
  - protobuf=4.25.3
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pygments=2.15.1
  - pyjwt=2.8.0
  - pyopenssl=24.2.1
  - pyparsing=3.0.9
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pysocks=1.7.1
  - python=3.8.20
  - python-dateutil=2.9.0post0
  - pytorch=1.12.0
  - pytorch-mutex=1.0
  - qt-main=5.15.2
  - re2=2022.04.01
  - readline=8.2
  - requests=2.32.3
  - requests-oauthlib=2.0.0
  - rsa=4.7.2
  - scikit-learn=1.3.0
  - scipy=1.10.1
  - setuptools=75.1.0
  - sip=6.7.12
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - tbb=2021.8.0
  - tensorboard=2.12.1
  - tensorboard-data-server=0.7.0
  - tensorboard-plugin-wit=1.8.1
  - termcolor=2.1.0
  - tesseract=5.2.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - toml=0.10.2
  - tomli=2.0.1
  - torchmetrics=0.9.3
  - torchvision=0.13.0
  - tornado=6.4.1
  - tqdm=4.66.5
  - traitlets=5.14.3
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - wcwidth=0.2.5
  - werkzeug=3.0.3
  - wheel=0.44.0
  - xkeyboard-config=2.44
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - yarl=1.11.0
  - zipp=3.20.2
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - annotated-types==0.7.0
      - beautifulsoup4==4.13.4
      - bokeh==3.1.1
      - clean-fid==0.1.35
      - colored-traceback==0.4.2
      - decorator==4.4.2
      - docker-pycreds==0.4.0
      - eval-type-backport==0.2.2
      - filelock==3.16.1
      - gdown==4.6.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - imageio-ffmpeg==0.5.1
      - jinja2==3.1.6
      - lmdb==1.6.2
      - lpips==0.1.4
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - moviepy==1.0.3
      - narwhals==1.40.0
      - pandas==2.0.3
      - plotly==6.1.1
      - prefetch-generator==1.0.3
      - proglog==0.1.12
      - psutil==7.0.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pytorch-fid==0.3.0
      - pytz==2025.2
      - pyyaml==6.0.2
      - rdkit==2024.3.5
      - rich==14.0.0
      - sentry-sdk==2.29.1
      - setproctitle==1.3.6
      - smmap==5.0.2
      - soundfile==0.13.1
      - soupsieve==2.7
      - torch-ema==0.3
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - wandb==0.19.11
      - xyzservices==2025.4.0
